# Generated by Django 4.1.2 on 2022-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_user_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="participant",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
